const DATA = window.IELTS_DATA;
const SKEY = 'ielts-marathon-state-v2';
const OLDKEY = 'ielts-marathon-state-v1';
const DAY = () => new Date().toISOString().slice(0,10);
const todayNum = () => Math.floor(Date.now()/86400000);
const defaultState = {profile:null,done:[],streak:0,lastStudy:null,notes:{},errors:[],flash:{},lastDay:1,xp:0,quiz:{},studyDates:[],missions:{},theme:'light'};
let oldState={}; try{oldState=JSON.parse(localStorage.getItem(OLDKEY)||'{}')}catch(e){}
let state={...defaultState,...oldState}; try{state={...state,...JSON.parse(localStorage.getItem(SKEY)||'{}')}}catch(e){}
state.done ||= []; state.notes ||= {}; state.errors ||= []; state.flash ||= {}; state.quiz ||= {}; state.studyDates ||= []; state.missions ||= {};
let route=location.hash.slice(1)||'dashboard';
let timer={seconds:900,running:false,id:null};
let flashIndex=0, flashReveal=false;
let quizSession=null;
let recorder=null,recordChunks=[],recordUrl=null;
const $=s=>document.querySelector(s);
const save=()=>localStorage.setItem(SKEY,JSON.stringify(state));
const esc=(s='')=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const fmtDate=d=>new Intl.DateTimeFormat('vi-VN',{day:'2-digit',month:'2-digit'}).format(new Date(d+'T00:00:00'));
function nav(r){route=r;location.hash=r;render();window.scrollTo({top:0,behavior:'smooth'})}
window.addEventListener('hashchange',()=>{route=location.hash.slice(1)||'dashboard';render()});
function toast(msg){let e=document.createElement('div');e.className='toast';e.textContent=msg;document.body.appendChild(e);setTimeout(()=>e.classList.add('show'),10);setTimeout(()=>{e.classList.remove('show');setTimeout(()=>e.remove(),250)},2200)}
function addXP(n){state.xp=(state.xp||0)+n;save()}
function markStudy(){const d=DAY();if(!state.studyDates.includes(d))state.studyDates.push(d);if(state.lastStudy!==d){const prev=new Date(Date.now()-86400000).toISOString().slice(0,10);state.streak=state.lastStudy===prev?(state.streak||0)+1:1;state.lastStudy=d;addXP(5)}save()}
function complete(day){if(!state.done.includes(day)){state.done.push(day);addXP(40);toast('+40 XP • Hoàn thành Ngày '+day)}state.lastDay=Math.min(21,day+1);markStudy();state.missions[DAY()]={...(state.missions[DAY()]||{}),lesson:true};save();render()}
function shell(body,title='IELTS Marathon'){
 const navs=[['dashboard','⌂','Hôm nay'],['roadmap','◫','Lộ trình'],['flashcards','◇','Ôn từ'],['errors','△','Lỗi sai'],['progress','↗','Tiến bộ'],['settings','⚙','Cài đặt']];
 return `<div class="shell"><aside class="sidebar"><div class="brand" onclick="nav('dashboard')"><div class="logo">IM</div><span>IELTS Marathon</span></div><nav>${navs.map(([r,i,l])=>`<button class="navbtn ${route.startsWith(r)?'active':''}" onclick="nav('${r}')"><span>${i}</span>${l}</button>`).join('')}</nav><div class="sidecard"><b>${state.xp||0} XP</b><small>Level ${level()} • ${xpToNext()} XP tới level tiếp theo</small><div class="mini-progress"><i style="width:${levelPct()}%"></i></div></div><div class="sidefoot">100% local • Không tài khoản • Không phí</div></aside><main class="main"><header class="topbar"><div><small class="eyebrow">IELTS MARATHON</small><h1>${esc(title)}</h1></div><div class="top-actions"><span class="pill">🔥 ${state.streak||0}</span><span class="pill xp">⚡ ${state.xp||0} XP</span></div></header><div class="content">${body}</div></main><nav class="mobile-nav">${navs.slice(0,5).map(([r,i,l])=>`<button class="${route.startsWith(r)?'active':''}" onclick="nav('${r}')"><span>${i}</span><small>${l}</small></button>`).join('')}</nav></div>`
}
function level(){return Math.floor((state.xp||0)/200)+1} function xpToNext(){return 200-(state.xp||0)%200} function levelPct(){return ((state.xp||0)%200)/2}
function onboarding(){document.body.innerHTML=`<div class="onboarding"><div class="onwrap"><section class="onintro"><span class="tag">21-DAY IELTS MARATHON</span><h1>15 phút mỗi ngày.<br><em>Tiến bộ nhìn thấy được.</em></h1><p>Biến bộ tài liệu 21 ngày thành một lộ trình ngắn gọn: học bài, làm quiz, ôn từ, ghi lỗi và theo dõi chuỗi ngày học — tất cả ngay trên thiết bị.</p><div class="feature-row"><span>✓ Không đăng nhập</span><span>✓ Không phí</span><span>✓ Không cần AI</span></div></section><section class="oncard"><h2>Thiết lập lộ trình</h2><div class="field"><label>Tên hiển thị</label><input id="name" placeholder="Ví dụ: Hải Anh"></div><div class="field"><label>Mục tiêu IELTS</label><select id="target"><option>6.0</option><option selected>6.5</option><option>7.0</option><option>7.5</option><option>8.0+</option></select></div><div class="field"><label>Nhịp học mỗi ngày</label><select id="mins"><option selected>15 phút</option><option>30 phút</option><option>45 phút</option></select></div><button class="primary wide" onclick="finishOnboarding()">Bắt đầu Ngày 1 →</button><small class="privacy">Dữ liệu được lưu trong trình duyệt của bạn.</small></section></div></div>`}
function finishOnboarding(){state.profile={name:$('#name').value.trim()||'Người học',target:$('#target').value,mins:$('#mins').value};state.xp=10;save();nav('dashboard')}
function nextLesson(){return DATA.lessons.find(x=>!state.done.includes(x.day))||DATA.lessons[20]}
function dailyMission(){const next=nextLesson(),due=dueCards().length,q=state.quiz[next.day];const lessonDone=state.done.includes(next.day),quizDone=q&&q.best>=60,reviewDone=(state.missions[DAY()]||{}).review;return {next,due,lessonDone,quizDone,reviewDone,items:[{done:lessonDone,label:`Học Ngày ${next.day}`,sub:next.title,action:`nav('lesson-${next.day}')`},{done:quizDone,label:'Quick Quiz 5 câu',sub:'Từ vựng của bài hôm nay',action:`nav('quiz-${next.day}')`},{done:reviewDone,label:'Ôn flashcard đến hạn',sub:`${due} thẻ đang chờ`,action:`nav('flashcards')`}]}}
function dashboard(){const m=dailyMission(),pct=Math.round(state.done.length/21*100),missionDone=m.items.filter(x=>x.done).length;return shell(`<section class="hero"><div class="hero-copy"><span class="tag darktag">DAY ${String(m.next.day).padStart(2,'0')} • ${esc(state.profile.mins||'15 phút')}</span><h2>Chào ${esc(state.profile.name)}.<br>Hôm nay chỉ cần <em>một phiên ngắn.</em></h2><p>${esc(m.next.title)} — hoàn thành bài học, làm quick quiz và ôn vài thẻ đến hạn. Không cần học dồn.</p><button class="hero-btn" onclick="nav('lesson-${m.next.day}')">Bắt đầu phiên hôm nay <span>→</span></button></div><div class="hero-ring"><div class="ring" style="--p:${pct}"><div><strong>${pct}%</strong><span>lộ trình</span></div></div><small>${state.done.length}/21 ngày hoàn thành</small></div></section><div class="dashgrid"><section><div class="section-title"><div><span class="eyebrow">DAILY MISSION</span><h2>3 việc cho hôm nay</h2></div><b class="mission-count">${missionDone}/3</b></div><div class="mission-list">${m.items.map((x,i)=>`<button class="mission ${x.done?'done':''}" onclick="${x.action}"><span class="check">${x.done?'✓':i+1}</span><span><b>${esc(x.label)}</b><small>${esc(x.sub)}</small></span><span class="arrow">→</span></button>`).join('')}</div></section><aside><div class="card snapshot"><span class="eyebrow">TỔNG QUAN</span><div class="metric"><strong>${state.streak||0}</strong><span>ngày streak</span></div><div class="metric"><strong>${quizAverage()}%</strong><span>quiz trung bình</span></div><div class="metric"><strong>${state.errors.filter(e=>!e.resolved).length}</strong><span>lỗi cần ôn</span></div><button class="textbtn" onclick="nav('progress')">Xem tiến bộ →</button></div></aside></div><div class="section-title"><div><span class="eyebrow">UP NEXT</span><h2>Những ngày tiếp theo</h2></div><button class="textbtn" onclick="nav('roadmap')">Xem 21 ngày</button></div><div class="grid">${DATA.lessons.filter(x=>x.day>=m.next.day).slice(0,3).map(dayCard).join('')}</div>`, 'Hôm nay')}
function dayCard(l){const done=state.done.includes(l.day),q=state.quiz[l.day];return `<article class="card daycard ${done?'isdone':''}"><div class="daytop"><span class="daynum">NGÀY ${String(l.day).padStart(2,'0')}</span>${done?'<span class="done">✓ Hoàn thành</span>':''}</div><h3>${esc(l.title)}</h3><div class="daymeta"><span>◷ 15 phút</span><span>${q?`Quiz ${q.best}%`:'Quiz chưa làm'}</span></div><button class="${done?'ghost':'primary'}" onclick="nav('lesson-${l.day}')">${done?'Học lại':'Vào bài'} →</button></article>`}
function roadmap(){return shell(`<div class="pagelead"><span class="eyebrow">21-DAY PLAN</span><h2>Lộ trình của bạn</h2><p>Mỗi ngày tập trung một mục tiêu nhỏ. Học theo thứ tự hoặc mở bất kỳ ngày nào khi cần ôn lại.</p></div><div class="road-progress"><div><b>${state.done.length}/21</b><span>đã xong</span></div><div class="progress"><i style="width:${state.done.length/21*100}%"></i></div><strong>${Math.round(state.done.length/21*100)}%</strong></div><div class="grid">${DATA.lessons.map(dayCard).join('')}</div>`,'Lộ trình 21 ngày')}
function headingClass(t){if(/^\d+\.\d+\s/.test(t)||/^SECTION\s/i.test(t)||/^Questions?\s/i.test(t)||/^Part\s[123]/i.test(t)||/^Nhiệm vụ\s/i.test(t)||/^Câu hỏi/i.test(t))return 'heading';if(/^>/.test(t)||/^(TRUE|FALSE|NOT GIVEN)/i.test(t))return 'prompt';return ''}
function blocksHtml(blocks){return blocks.map(b=>{if(b.type==='p')return `<div class="lesson-block p ${headingClass(b.text)}">${esc(b.text)}</div>`;return `<div class="tablewrap"><table>${b.rows.map((r,ri)=>`<tr>${r.map(c=>`<td>${esc(c)}</td>`).join('')}</tr>`).join('')}</table></div>`}).join('')}
function timerHtml(){return `<div class="card timer"><span class="eyebrow">FOCUS TIMER</span><div class="clock" id="clock">${fmt(timer.seconds)}</div><div class="toolrow center"><button class="primary" onclick="toggleTimer()">${timer.running?'Tạm dừng':'Bắt đầu'}</button><button class="ghost" onclick="resetTimer()">15:00</button></div></div>`}
function fmt(s){return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}
function toggleTimer(){if(timer.running){clearInterval(timer.id);timer.running=false;render()}else{timer.running=true;markStudy();timer.id=setInterval(()=>{timer.seconds--;const c=$('#clock');if(c)c.textContent=fmt(Math.max(0,timer.seconds));if(timer.seconds<=0){clearInterval(timer.id);timer.running=false;addXP(15);toast('🎉 Hoàn thành 15 phút • +15 XP');render()}},1000);const b=document.querySelector('.timer .primary');if(b)b.textContent='Tạm dừng'}}
function resetTimer(){if(timer.id)clearInterval(timer.id);timer={seconds:900,running:false,id:null};render()}
function lesson(day){const l=DATA.lessons.find(x=>x.day===day);if(!l)return roadmap();state.lastDay=day;save();const note=state.notes[day]||'';return shell(`<div class="lesson-head"><div><span class="daynum">NGÀY ${String(day).padStart(2,'0')}</span><h2>${esc(l.title)}</h2><p>Đọc theo nhịp của bạn. Không cần hoàn thành hết trong một lượt.</p></div><button class="primary" onclick="nav('quiz-${day}')">Quick Quiz →</button></div><div class="lesson-layout"><article class="card lesson"><div class="readingbar"><span>📖 Nội dung bài học</span><button class="textbtn" onclick="toggleAnswers()">Đáp án / bài mẫu</button></div><div id="maincontent">${blocksHtml(l.main)}</div><div class="answerbox hidden" id="answerbox"><div class="answerhead"><b>Đáp án & bài mẫu</b><span>Dùng sau khi đã tự làm</span></div><div class="answers-content">${blocksHtml(l.answers)}</div></div><div class="completebar"><div><b>${state.done.includes(day)?'✓ Đã hoàn thành':'Hoàn thành bài hôm nay?'}</b><small>${state.done.includes(day)?'Bạn vẫn có thể học lại bất cứ lúc nào.':'Đánh dấu xong để cập nhật lộ trình và nhận 40 XP.'}</small></div><button class="${state.done.includes(day)?'ghost':'primary'}" onclick="complete(${day})">${state.done.includes(day)?'Đã xong':'✓ Hoàn thành'}</button></div></article><aside class="lesson-tools">${timerHtml()}<div class="card toolcard"><span class="eyebrow">GHI CHÚ</span><textarea class="notes" id="notes" placeholder="Từ mới, ý cần nhớ..." oninput="saveNote(${day},this.value)">${esc(note)}</textarea><small class="muted">Tự động lưu trên thiết bị</small></div><div class="card toolcard"><span class="eyebrow">LỖI SAI</span><input id="err" placeholder="Ví dụ: nhầm False / Not Given"><button class="secondary wide" onclick="quickError(${day})">+ Thêm vào sổ lỗi</button></div><div class="card toolcard"><span class="eyebrow">SPEAKING RECORDER</span><p class="muted sm">Ghi âm ngay trên trình duyệt. Audio không được tải lên đâu cả.</p><div class="toolrow"><button class="ghost" id="recordBtn" onclick="toggleRecord()">● Ghi âm</button><button class="ghost" onclick="stopAndDownload()">↓ Lưu file</button></div><audio id="audioPreview" controls class="audio"></audio></div></aside></div>`,`Ngày ${day} · ${l.title}`)}
function saveNote(day,v){state.notes[day]=v;save();markStudy()}
function toggleAnswers(){const e=$('#answerbox');e.classList.toggle('hidden');markStudy()}
function quickError(day){const v=$('#err').value.trim();if(!v)return;state.errors.unshift({day,error:v,fix:'',resolved:false,created:DAY(),source:'manual'});save();$('#err').value='';toast('Đã thêm vào Sổ lỗi sai')}
async function toggleRecord(){if(recorder&&recorder.state==='recording'){recorder.stop();return}if(!navigator.mediaDevices||!window.MediaRecorder){toast('Trình duyệt này chưa hỗ trợ ghi âm');return}try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});recordChunks=[];recorder=new MediaRecorder(stream);recorder.ondataavailable=e=>recordChunks.push(e.data);recorder.onstop=()=>{const blob=new Blob(recordChunks,{type:recorder.mimeType||'audio/webm'});if(recordUrl)URL.revokeObjectURL(recordUrl);recordUrl=URL.createObjectURL(blob);const a=$('#audioPreview');if(a){a.src=recordUrl;a.style.display='block'}stream.getTracks().forEach(t=>t.stop());const b=$('#recordBtn');if(b)b.textContent='● Ghi âm lại';addXP(5);markStudy()};recorder.start();$('#recordBtn').textContent='■ Dừng ghi';markStudy()}catch(e){toast('Cần cho phép microphone để ghi âm')}}
function stopAndDownload(){if(recorder&&recorder.state==='recording'){toast('Hãy dừng ghi âm trước');return}if(!recordChunks.length||!recordUrl){toast('Chưa có bản ghi âm');return}const a=document.createElement('a');a.href=recordUrl;a.download=`ielts-speaking-${DAY()}.webm`;a.click()}
function makeQuiz(day){const pool=DATA.flashcards.filter(c=>c.day===day);const base=(pool.length>=5?pool:DATA.flashcards).slice();shuffle(base);const qs=base.slice(0,5).map((c,idx)=>{let ds=DATA.flashcards.filter(x=>x.back!==c.back);shuffle(ds);let opts=[c.back,...ds.slice(0,3).map(x=>x.back)];shuffle(opts);return {front:c.front,answer:c.back,example:c.example||'',opts}});return {day,qs,index:0,score:0,answered:false,selected:null,wrong:[]}}
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function quiz(day){if(!quizSession||quizSession.day!==day)quizSession=makeQuiz(day);const q=quizSession;if(q.index>=q.qs.length)return quizResult(q);const item=q.qs[q.index],progress=q.index/q.qs.length*100;return shell(`<div class="quizwrap"><div class="quiztop"><div><span class="eyebrow">QUICK QUIZ • NGÀY ${day}</span><h2>Câu ${q.index+1}/5</h2></div><span class="scorepill">${q.score} đúng</span></div><div class="progress quizprogress"><i style="width:${progress}%"></i></div><div class="card quizcard"><span class="quizlabel">Chọn nghĩa phù hợp nhất</span><h3>${esc(item.front)}</h3><div class="choices">${item.opts.map((o,i)=>`<button class="choice ${q.answered?(o===item.answer?'correct':o===q.selected?'wrong':''):''}" ${q.answered?'disabled':''} onclick="answerQuiz(${JSON.stringify(o).replace(/"/g,'&quot;')})"><span>${String.fromCharCode(65+i)}</span>${esc(o)}</button>`).join('')}</div>${q.answered?`<div class="feedback ${q.selected===item.answer?'good':'bad'}"><b>${q.selected===item.answer?'✓ Chính xác':'✕ Chưa đúng'}</b><p>${item.example?esc(item.example):'Đáp án: '+esc(item.answer)}</p></div><button class="primary wide" onclick="nextQuiz()">${q.index===4?'Xem kết quả':'Câu tiếp theo'} →</button>`:''}</div></div>`,`Quiz ngày ${day}`)}
function answerQuiz(encoded){if(quizSession.answered)return;const item=quizSession.qs[quizSession.index];quizSession.selected=encoded;quizSession.answered=true;if(encoded===item.answer){quizSession.score++;addXP(4)}else quizSession.wrong.push({front:item.front,answer:item.answer,selected:encoded});markStudy();render()}
function nextQuiz(){quizSession.index++;quizSession.answered=false;quizSession.selected=null;render()}
function quizResult(q){const pct=q.score*20,prev=state.quiz[q.day]?.best||0;state.quiz[q.day]={best:Math.max(prev,pct),last:pct,date:DAY()};if(pct>=60)state.missions[DAY()]={...(state.missions[DAY()]||{}),quiz:true};q.wrong.forEach(w=>{if(!state.errors.some(e=>e.source==='quiz'&&e.day===q.day&&e.error===w.front&&!e.resolved))state.errors.unshift({day:q.day,error:`${w.front} → đã chọn: ${w.selected}`,fix:`Đáp án: ${w.answer}`,resolved:false,created:DAY(),source:'quiz'})});if(!q.saved){addXP(pct===100?20:10);q.saved=true;save()}return shell(`<div class="result card"><div class="resultscore ${pct>=60?'pass':'retry'}"><strong>${pct}%</strong><span>${pct>=80?'Rất tốt!':pct>=60?'Đạt mục tiêu hôm nay':'Nên thử lại'}</span></div><h2>${q.score}/5 câu đúng</h2><p>${q.wrong.length?`${q.wrong.length} câu sai đã tự động được đưa vào Sổ lỗi để bạn ôn lại.`:'Không có lỗi nào trong lượt này.'}</p><div class="result-actions"><button class="primary" onclick="quizSession=makeQuiz(${q.day});render()">Làm lượt mới</button><button class="ghost" onclick="nav('errors')">Xem lỗi sai</button><button class="ghost" onclick="nav('dashboard')">Về hôm nay</button></div></div>`,`Kết quả Quiz · Ngày ${q.day}`)}
function dueCards(){return DATA.flashcards.map((c,i)=>({...c,_i:i})).filter(c=>{const x=state.flash[c._i];return !x||x.due<=todayNum()})}
function flashcards(){const cards=dueCards(),c=cards[flashIndex%Math.max(1,cards.length)];if(!c){state.missions[DAY()]={...(state.missions[DAY()]||{}),review:true};save();return shell(`<div class="celebrate card"><div class="bigemoji">✓</div><h2>Hôm nay ôn xong rồi!</h2><p>Không còn flashcard nào đến hạn. Quay lại ngày mai để tiếp tục vòng lặp ghi nhớ.</p><button class="primary" onclick="nav('dashboard')">Về Daily Mission</button></div>`,'Ôn từ vựng')}return shell(`<div class="flashwrap"><div class="flashhead"><div><span class="eyebrow">SPACED REPETITION</span><h2>${cards.length} thẻ đến hạn</h2></div><span class="pill">Nguồn: Ngày ${c.day}</span></div><button class="flash card ${flashReveal?'revealed':''}" onclick="flashReveal=!flashReveal;render()">${flashReveal?`<div><span class="eyebrow">NGHĨA</span><div class="back">${esc(c.back)}</div>${c.example?`<p>${esc(c.example)}</p>`:''}<small>Chọn mức độ nhớ bên dưới</small></div>`:`<div><span class="eyebrow">TỪ / CỤM TỪ</span><div class="front">${esc(c.front)}</div><small>Chạm để lật thẻ</small></div>`}</button>${flashReveal?`<div class="rating"><button onclick="rateCard(${c._i},1)"><b>Quên</b><small>1 ngày</small></button><button onclick="rateCard(${c._i},3)"><b>Khó</b><small>3 ngày</small></button><button onclick="rateCard(${c._i},7)"><b>Nhớ</b><small>7 ngày</small></button><button onclick="rateCard(${c._i},14)"><b>Dễ</b><small>14 ngày</small></button></div>`:''}</div>`,'Flashcards SRS')}
function rateCard(i,days){const t=todayNum();state.flash[i]={due:t+days,last:t,interval:days};addXP(days>=7?3:2);flashIndex++;flashReveal=false;markStudy();if(dueCards().length<=1)state.missions[DAY()]={...(state.missions[DAY()]||{}),review:true};save();render()}
function errors(){const open=state.errors.filter(e=>!e.resolved),resolved=state.errors.filter(e=>e.resolved);return shell(`<div class="pagelead"><span class="eyebrow">ERROR NOTEBOOK</span><h2>Ôn đúng chỗ đang mất điểm</h2><p>Câu sai trong Quick Quiz được thêm tự động. Lỗi tự ghi cũng xuất hiện ở đây.</p></div><div class="tabs"><button class="active">Cần ôn (${open.length})</button><button onclick="showResolved()">Đã xử lý (${resolved.length})</button><button class="primary smallbtn" onclick="addError()">+ Thêm lỗi</button></div><div id="errorList" class="error-list">${errorList(open,false)}</div>`,'Sổ tay lỗi sai')}
function errorList(list,resolved){return list.length?list.map(e=>{const i=state.errors.indexOf(e);return `<article class="card error-card"><div class="error-meta"><span class="badge ${e.source==='quiz'?'auto':''}">${e.source==='quiz'?'Tự động':'Tự ghi'}</span>${e.day?`<span>Ngày ${e.day}</span>`:''}<span>${esc(e.created||'')}</span></div><input value="${esc(e.error)}" onchange="editError(${i},'error',this.value)" placeholder="Lỗi cụ thể"><textarea onchange="editError(${i},'fix',this.value)" placeholder="Cách sửa / điều cần nhớ">${esc(e.fix||'')}</textarea><div class="toolrow"><button class="${resolved?'ghost':'primary'}" onclick="resolveError(${i},${!resolved})">${resolved?'↩ Mở lại':'✓ Đã hiểu'}</button><button class="textbtn danger" onclick="removeError(${i})">Xóa</button></div></article>`}).join(''):'<div class="card empty">Không có mục nào ở đây.</div>'}
function showResolved(){const list=state.errors.filter(e=>e.resolved);$('#errorList').innerHTML=errorList(list,true);document.querySelectorAll('.tabs button').forEach(b=>b.classList.remove('active'));document.querySelectorAll('.tabs button')[1].classList.add('active')}
function addError(){state.errors.unshift({day:null,error:'',fix:'',resolved:false,created:DAY(),source:'manual'});save();render()} function editError(i,k,v){state.errors[i][k]=v;save()} function removeError(i){state.errors.splice(i,1);save();render()} function resolveError(i,v){state.errors[i].resolved=v;if(v)addXP(5);save();render()}
function quizAverage(){const vals=Object.values(state.quiz).map(x=>x.best).filter(Number.isFinite);return vals.length?Math.round(vals.reduce((a,b)=>a+b,0)/vals.length):0}
function progress(){const qavg=quizAverage(),completion=Math.round(state.done.length/21*100),reviewed=Object.keys(state.flash).length,readiness=Math.round(completion*.55+qavg*.3+Math.min(100,reviewed/Math.max(1,DATA.flashcards.length)*100)*.15);const last14=[...Array(14)].map((_,i)=>{const d=new Date(Date.now()-(13-i)*86400000).toISOString().slice(0,10);return {d,active:state.studyDates.includes(d)}});return shell(`<div class="pagelead"><span class="eyebrow">PROGRESS</span><h2>Nhìn thấy quá trình, không đoán mò</h2><p>Chỉ số sẵn sàng bên dưới là thước đo nội bộ của lộ trình, <b>không phải dự đoán band IELTS</b>.</p></div><div class="progress-cards"><div class="card bigmetric"><span>Hoàn thành</span><strong>${completion}%</strong><small>${state.done.length}/21 ngày</small></div><div class="card bigmetric"><span>Quiz trung bình</span><strong>${qavg}%</strong><small>${Object.keys(state.quiz).length} ngày đã quiz</small></div><div class="card bigmetric"><span>Đã ôn</span><strong>${reviewed}</strong><small>/ ${DATA.flashcards.length} flashcards</small></div><div class="card bigmetric accent"><span>Độ sẵn sàng</span><strong>${readiness}%</strong><small>theo tiến độ + quiz + SRS</small></div></div><div class="card activity"><div class="section-title"><div><span class="eyebrow">14 NGÀY GẦN NHẤT</span><h2>Nhịp học</h2></div><span class="pill">🔥 ${state.streak||0} streak</span></div><div class="heatmap">${last14.map(x=>`<div class="heat ${x.active?'active':''}" title="${x.d}"><i>${new Date(x.d+'T00:00').getDate()}</i><small>${['CN','T2','T3','T4','T5','T6','T7'][new Date(x.d+'T00:00').getDay()]}</small></div>`).join('')}</div></div><div class="card achievement"><span class="eyebrow">THÀNH TỰU</span><div class="achievements">${achievement('🔥','Bắt đầu chuỗi',state.streak>=1)}${achievement('⚡','100 XP',state.xp>=100)}${achievement('🎯','Quiz 100%',Object.values(state.quiz).some(x=>x.best===100))}${achievement('📚','7 ngày hoàn thành',state.done.length>=7)}${achievement('🏁','21 ngày hoàn thành',state.done.length>=21)}</div></div>`,'Tiến bộ')}
function achievement(icon,label,ok){return `<div class="achievement-item ${ok?'unlocked':''}"><span>${icon}</span><b>${label}</b><small>${ok?'Đã mở khóa':'Chưa mở'}</small></div>`}
function settings(){return shell(`<div class="settings-grid"><div class="card settings-card"><span class="eyebrow">HỒ SƠ</span><h2>Cài đặt học</h2><div class="field"><label>Tên</label><input id="sname" value="${esc(state.profile.name)}"></div><div class="field"><label>Mục tiêu IELTS</label><input id="starget" value="${esc(state.profile.target)}"></div><div class="field"><label>Nhịp học</label><select id="smins"><option ${state.profile.mins==='15 phút'?'selected':''}>15 phút</option><option ${state.profile.mins==='30 phút'?'selected':''}>30 phút</option><option ${state.profile.mins==='45 phút'?'selected':''}>45 phút</option></select></div><button class="primary" onclick="saveSettings()">Lưu thay đổi</button></div><div class="card settings-card"><span class="eyebrow">DỮ LIỆU</span><h2>Sao lưu</h2><p class="muted">Xuất tiến độ thành file JSON để chuyển sang máy khác hoặc lưu phòng khi xóa dữ liệu trình duyệt.</p><div class="toolrow"><button class="ghost" onclick="exportData()">↓ Xuất dữ liệu</button><label class="ghost upload">↑ Nhập dữ liệu<input type="file" accept="application/json" onchange="importData(this.files[0])"></label></div><hr><button class="textbtn danger" onclick="resetAll()">Xóa toàn bộ dữ liệu học</button></div></div>`,'Cài đặt')}
function saveSettings(){state.profile.name=$('#sname').value.trim()||state.profile.name;state.profile.target=$('#starget').value.trim()||state.profile.target;state.profile.mins=$('#smins').value;save();toast('Đã lưu cài đặt')}
function exportData(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`ielts-marathon-backup-${DAY()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function importData(file){if(!file)return;const r=new FileReader();r.onload=()=>{try{state={...defaultState,...JSON.parse(r.result)};save();toast('Đã nhập dữ liệu');render()}catch(e){toast('File sao lưu không hợp lệ')}};r.readAsText(file)}
function resetAll(){if(confirm('Xóa toàn bộ tiến độ, ghi chú và lỗi sai trên thiết bị này?')){localStorage.removeItem(SKEY);localStorage.removeItem(OLDKEY);state=structuredClone(defaultState);render()}}
function render(){if(!state.profile){onboarding();return}route=location.hash.slice(1)||route||'dashboard';let html;if(route==='dashboard')html=dashboard();else if(route==='roadmap')html=roadmap();else if(route==='flashcards')html=flashcards();else if(route==='errors')html=errors();else if(route==='progress')html=progress();else if(route==='settings')html=settings();else if(route.startsWith('lesson-'))html=lesson(Number(route.split('-')[1]));else if(route.startsWith('quiz-'))html=quiz(Number(route.split('-')[1]));else html=dashboard();document.body.innerHTML=html}
render();
